// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: competitions.sql

package db

import (
	"context"
	"database/sql"
)

const getCompProviderCode = `-- name: GetCompProviderCode :one
SELECT provider_id FROM id_crosswalk
WHERE comp_code = ?1 AND provider = ?2
LIMIT 1
`

type GetCompProviderCodeParams struct {
	CompCode sql.NullString `json:"comp_code"`
	Provider string         `json:"provider"`
}

func (q *Queries) GetCompProviderCode(ctx context.Context, arg GetCompProviderCodeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCompProviderCode, arg.CompCode, arg.Provider)
	var provider_id string
	err := row.Scan(&provider_id)
	return provider_id, err
}

const getCompetitionByCode = `-- name: GetCompetitionByCode :one
SELECT id, code, name, country, enabled FROM competitions WHERE code = ? LIMIT 1
`

func (q *Queries) GetCompetitionByCode(ctx context.Context, code string) (Competition, error) {
	row := q.db.QueryRowContext(ctx, getCompetitionByCode, code)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Country,
		&i.Enabled,
	)
	return i, err
}

const getEnabledCompetitions = `-- name: GetEnabledCompetitions :many
SELECT id, code, name, country, enabled FROM competitions WHERE enabled = 1 ORDER BY code ASC
`

func (q *Queries) GetEnabledCompetitions(ctx context.Context) ([]Competition, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledCompetitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Competition{}
	for rows.Next() {
		var i Competition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Country,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompetition = `-- name: UpsertCompetition :one
INSERT INTO competitions (code, name, country, enabled)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(code) DO UPDATE SET
    name = excluded.name,
    country = excluded.country,
    enabled = excluded.enabled
RETURNING id, code, name, country, enabled
`

type UpsertCompetitionParams struct {
	Code    string         `json:"code"`
	Name    string         `json:"name"`
	Country sql.NullString `json:"country"`
	Enabled int64          `json:"enabled"`
}

func (q *Queries) UpsertCompetition(ctx context.Context, arg UpsertCompetitionParams) (Competition, error) {
	row := q.db.QueryRowContext(ctx, upsertCompetition,
		arg.Code,
		arg.Name,
		arg.Country,
		arg.Enabled,
	)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Country,
		&i.Enabled,
	)
	return i, err
}
