// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package db

import (
	"context"
	"database/sql"
)

const listFinishedByLeagueAndSeason = `-- name: ListFinishedByLeagueAndSeason :many
SELECT m.id, m.competition_id, m.external_id, m.season, m.utc_kickoff, m.status, m.home_team_id, m.away_team_id, m.home_goals, m.away_goals, m.minute, h.name AS home_team_name, a.name AS away_team_name
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.competition_id = ?1 AND m.season = ?2 AND m.status = 'FINISHED'
ORDER BY m.utc_kickoff DESC, m.id DESC
`

type ListFinishedByLeagueAndSeasonParams struct {
	CompetitionID int64  `json:"competition_id"`
	Season        string `json:"season"`
}

type ListFinishedByLeagueAndSeasonRow struct {
	ID            int64          `json:"id"`
	CompetitionID int64          `json:"competition_id"`
	ExternalID    sql.NullString `json:"external_id"`
	Season        string         `json:"season"`
	UtcKickoff    string         `json:"utc_kickoff"`
	Status        string         `json:"status"`
	HomeTeamID    int64          `json:"home_team_id"`
	AwayTeamID    int64          `json:"away_team_id"`
	HomeGoals     sql.NullInt64  `json:"home_goals"`
	AwayGoals     sql.NullInt64  `json:"away_goals"`
	Minute        sql.NullInt64  `json:"minute"`
	HomeTeamName  string         `json:"home_team_name"`
	AwayTeamName  string         `json:"away_team_name"`
}

func (q *Queries) ListFinishedByLeagueAndSeason(ctx context.Context, arg ListFinishedByLeagueAndSeasonParams) ([]ListFinishedByLeagueAndSeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedByLeagueAndSeason, arg.CompetitionID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinishedByLeagueAndSeasonRow{}
	for rows.Next() {
		var i ListFinishedByLeagueAndSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionID,
			&i.ExternalID,
			&i.Season,
			&i.UtcKickoff,
			&i.Status,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Minute,
			&i.HomeTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFixturesByLeagueAndSeason = `-- name: ListFixturesByLeagueAndSeason :many
SELECT m.id, m.competition_id, m.external_id, m.season, m.utc_kickoff, m.status, m.home_team_id, m.away_team_id, m.home_goals, m.away_goals, m.minute, h.name AS home_team_name, a.name AS away_team_name
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.competition_id = ?1 AND m.season = ?2
ORDER BY m.utc_kickoff ASC, m.id ASC
`

type ListFixturesByLeagueAndSeasonParams struct {
	CompetitionID int64  `json:"competition_id"`
	Season        string `json:"season"`
}

type ListFixturesByLeagueAndSeasonRow struct {
	ID            int64          `json:"id"`
	CompetitionID int64          `json:"competition_id"`
	ExternalID    sql.NullString `json:"external_id"`
	Season        string         `json:"season"`
	UtcKickoff    string         `json:"utc_kickoff"`
	Status        string         `json:"status"`
	HomeTeamID    int64          `json:"home_team_id"`
	AwayTeamID    int64          `json:"away_team_id"`
	HomeGoals     sql.NullInt64  `json:"home_goals"`
	AwayGoals     sql.NullInt64  `json:"away_goals"`
	Minute        sql.NullInt64  `json:"minute"`
	HomeTeamName  string         `json:"home_team_name"`
	AwayTeamName  string         `json:"away_team_name"`
}

func (q *Queries) ListFixturesByLeagueAndSeason(ctx context.Context, arg ListFixturesByLeagueAndSeasonParams) ([]ListFixturesByLeagueAndSeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, listFixturesByLeagueAndSeason, arg.CompetitionID, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFixturesByLeagueAndSeasonRow{}
	for rows.Next() {
		var i ListFixturesByLeagueAndSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionID,
			&i.ExternalID,
			&i.Season,
			&i.UtcKickoff,
			&i.Status,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Minute,
			&i.HomeTeamName,
			&i.AwayTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
