// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestSeasonByCompetition = `-- name: GetLatestSeasonByCompetition :one
SELECT season FROM matches
WHERE competition_id = ?
ORDER BY season DESC
LIMIT 1
`

func (q *Queries) GetLatestSeasonByCompetition(ctx context.Context, competitionID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestSeasonByCompetition, competitionID)
	var season string
	err := row.Scan(&season)
	return season, err
}

const getLiveMatches = `-- name: GetLiveMatches :many
SELECT id, competition_id, external_id, season, utc_kickoff, status, home_team_id, away_team_id, home_goals, away_goals, minute FROM matches
WHERE status = 'LIVE'
ORDER BY utc_kickoff ASC, id ASC
`

func (q *Queries) GetLiveMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getLiveMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.CompetitionID,
			&i.ExternalID,
			&i.Season,
			&i.UtcKickoff,
			&i.Status,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.Minute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, competition_id, external_id, season, utc_kickoff, status, home_team_id, away_team_id, home_goals, away_goals, minute FROM matches WHERE id = ? LIMIT 1
`

func (q *Queries) GetMatchByID(ctx context.Context, id int64) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.ExternalID,
		&i.Season,
		&i.UtcKickoff,
		&i.Status,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.Minute,
	)
	return i, err
}

const getMatchEvents = `-- name: GetMatchEvents :many
SELECT id, match_id, minute, type, side, player, detail FROM match_events
WHERE match_id = ?
ORDER BY minute ASC, id ASC
`

func (q *Queries) GetMatchEvents(ctx context.Context, matchID int64) ([]MatchEvent, error) {
	rows, err := q.db.QueryContext(ctx, getMatchEvents, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchEvent{}
	for rows.Next() {
		var i MatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Minute,
			&i.Type,
			&i.Side,
			&i.Player,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMatchEvent = `-- name: InsertMatchEvent :one
INSERT INTO match_events (match_id, minute, type, side, player, detail)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertMatchEventParams struct {
	MatchID int64          `json:"match_id"`
	Minute  int64          `json:"minute"`
	Type    string         `json:"type"`
	Side    string         `json:"side"`
	Player  sql.NullString `json:"player"`
	Detail  sql.NullString `json:"detail"`
}

func (q *Queries) InsertMatchEvent(ctx context.Context, arg InsertMatchEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMatchEvent,
		arg.MatchID,
		arg.Minute,
		arg.Type,
		arg.Side,
		arg.Player,
		arg.Detail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateMatchScore = `-- name: UpdateMatchScore :exec
UPDATE matches
SET home_goals = ?, away_goals = ?, minute = ?
WHERE id = ?
`

type UpdateMatchScoreParams struct {
	HomeGoals sql.NullInt64 `json:"home_goals"`
	AwayGoals sql.NullInt64 `json:"away_goals"`
	Minute    sql.NullInt64 `json:"minute"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchScore,
		arg.HomeGoals,
		arg.AwayGoals,
		arg.Minute,
		arg.ID,
	)
	return err
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (
    competition_id, external_id, season, utc_kickoff, status,
    home_team_id, away_team_id, home_goals, away_goals, minute
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(external_id) DO UPDATE SET
    status = excluded.status,
    minute = excluded.minute,
    home_goals = excluded.home_goals,
    away_goals = excluded.away_goals
RETURNING id, competition_id, external_id, season, utc_kickoff, status, home_team_id, away_team_id, home_goals, away_goals, minute
`

type UpsertMatchParams struct {
	CompetitionID int64          `json:"competition_id"`
	ExternalID    sql.NullString `json:"external_id"`
	Season        string         `json:"season"`
	UtcKickoff    string         `json:"utc_kickoff"`
	Status        string         `json:"status"`
	HomeTeamID    int64          `json:"home_team_id"`
	AwayTeamID    int64          `json:"away_team_id"`
	HomeGoals     sql.NullInt64  `json:"home_goals"`
	AwayGoals     sql.NullInt64  `json:"away_goals"`
	Minute        sql.NullInt64  `json:"minute"`
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, upsertMatch,
		arg.CompetitionID,
		arg.ExternalID,
		arg.Season,
		arg.UtcKickoff,
		arg.Status,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomeGoals,
		arg.AwayGoals,
		arg.Minute,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.ExternalID,
		&i.Season,
		&i.UtcKickoff,
		&i.Status,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeGoals,
		&i.AwayGoals,
		&i.Minute,
	)
	return i, err
}
