// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Competition struct {
	ID      int64          `json:"id"`
	Code    string         `json:"code"`
	Name    string         `json:"name"`
	Country sql.NullString `json:"country"`
	Enabled int64          `json:"enabled"`
}

type EloRating struct {
	TeamID    int64   `json:"team_id"`
	Rating    float64 `json:"rating"`
	UpdatedAt string  `json:"updated_at"`
}

type IDCrosswalk struct {
	TeamID     sql.NullInt64  `json:"team_id"`
	CompCode   sql.NullString `json:"comp_code"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
}

type Match struct {
	ID            int64          `json:"id"`
	CompetitionID int64          `json:"competition_id"`
	ExternalID    sql.NullString `json:"external_id"`
	Season        string         `json:"season"`
	UtcKickoff    string         `json:"utc_kickoff"`
	Status        string         `json:"status"`
	HomeTeamID    int64          `json:"home_team_id"`
	AwayTeamID    int64          `json:"away_team_id"`
	HomeGoals     sql.NullInt64  `json:"home_goals"`
	AwayGoals     sql.NullInt64  `json:"away_goals"`
	Minute        sql.NullInt64  `json:"minute"`
}

type MatchEvent struct {
	ID      int64          `json:"id"`
	MatchID int64          `json:"match_id"`
	Minute  int64          `json:"minute"`
	Type    string         `json:"type"`
	Side    string         `json:"side"`
	Player  sql.NullString `json:"player"`
	Detail  sql.NullString `json:"detail"`
}

type Team struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	ShortName sql.NullString `json:"short_name"`
	Country   sql.NullString `json:"country"`
}

type WinProbSnapshot struct {
	ID      int64   `json:"id"`
	MatchID int64   `json:"match_id"`
	Minute  int64   `json:"minute"`
	Home    float64 `json:"home"`
	Draw    float64 `json:"draw"`
	Away    float64 `json:"away"`
}
