// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probabilities.sql

package db

import (
	"context"
)

const insertWinProbSnapshot = `-- name: InsertWinProbSnapshot :exec
INSERT INTO win_prob_snapshots (match_id, minute, home, draw, away)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(match_id, minute) DO UPDATE SET
    home = excluded.home,
    draw = excluded.draw,
    away = excluded.away
`

type InsertWinProbSnapshotParams struct {
	MatchID int64   `json:"match_id"`
	Minute  int64   `json:"minute"`
	Home    float64 `json:"home"`
	Draw    float64 `json:"draw"`
	Away    float64 `json:"away"`
}

func (q *Queries) InsertWinProbSnapshot(ctx context.Context, arg InsertWinProbSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertWinProbSnapshot,
		arg.MatchID,
		arg.Minute,
		arg.Home,
		arg.Draw,
		arg.Away,
	)
	return err
}

const listWinProbSnapshotsByMatch = `-- name: ListWinProbSnapshotsByMatch :many
SELECT id, match_id, minute, home, draw, away FROM win_prob_snapshots
WHERE match_id = ?
ORDER BY minute ASC
`

func (q *Queries) ListWinProbSnapshotsByMatch(ctx context.Context, matchID int64) ([]WinProbSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listWinProbSnapshotsByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WinProbSnapshot{}
	for rows.Next() {
		var i WinProbSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.Minute,
			&i.Home,
			&i.Draw,
			&i.Away,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
