// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const getEloRating = `-- name: GetEloRating :one
SELECT rating, updated_at FROM elo_ratings WHERE team_id = ?
`

type GetEloRatingRow struct {
	Rating    float64 `json:"rating"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) GetEloRating(ctx context.Context, teamID int64) (GetEloRatingRow, error) {
	row := q.db.QueryRowContext(ctx, getEloRating, teamID)
	var i GetEloRatingRow
	err := row.Scan(&i.Rating, &i.UpdatedAt)
	return i, err
}

const getOrCreateTeam = `-- name: GetOrCreateTeam :one
INSERT INTO teams (name, short_name, country)
VALUES (?1, ?2, ?3)
ON CONFLICT(name) DO UPDATE SET
    short_name = excluded.short_name,
    country = excluded.country
RETURNING id, name, short_name, country
`

type GetOrCreateTeamParams struct {
	Name      string         `json:"name"`
	ShortName sql.NullString `json:"short_name"`
	Country   sql.NullString `json:"country"`
}

func (q *Queries) GetOrCreateTeam(ctx context.Context, arg GetOrCreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTeam, arg.Name, arg.ShortName, arg.Country)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Country,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, short_name, country FROM teams WHERE id = ? LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Country,
	)
	return i, err
}

const getTeamCrosswalk = `-- name: GetTeamCrosswalk :many
SELECT team_id, comp_code, provider, provider_id FROM id_crosswalk WHERE team_id = ?
`

func (q *Queries) GetTeamCrosswalk(ctx context.Context, teamID sql.NullInt64) ([]IDCrosswalk, error) {
	rows, err := q.db.QueryContext(ctx, getTeamCrosswalk, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IDCrosswalk{}
	for rows.Next() {
		var i IDCrosswalk
		if err := rows.Scan(
			&i.TeamID,
			&i.CompCode,
			&i.Provider,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedBetweenTeams = `-- name: ListFinishedBetweenTeams :many
SELECT m.id, m.season, m.utc_kickoff, m.home_team_id, m.away_team_id,
       m.home_goals, m.away_goals,
       h.name AS home_name, a.name AS away_name
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.status = 'FINISHED'
  AND ((m.home_team_id = ?1 AND m.away_team_id = ?2)
    OR (m.home_team_id = ?2 AND m.away_team_id = ?1))
ORDER BY m.utc_kickoff DESC, m.id DESC
`

type ListFinishedBetweenTeamsParams struct {
	TeamA int64 `json:"team_a"`
	TeamB int64 `json:"team_b"`
}

type ListFinishedBetweenTeamsRow struct {
	ID         int64         `json:"id"`
	Season     string        `json:"season"`
	UtcKickoff string        `json:"utc_kickoff"`
	HomeTeamID int64         `json:"home_team_id"`
	AwayTeamID int64         `json:"away_team_id"`
	HomeGoals  sql.NullInt64 `json:"home_goals"`
	AwayGoals  sql.NullInt64 `json:"away_goals"`
	HomeName   string        `json:"home_name"`
	AwayName   string        `json:"away_name"`
}

func (q *Queries) ListFinishedBetweenTeams(ctx context.Context, arg ListFinishedBetweenTeamsParams) ([]ListFinishedBetweenTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedBetweenTeams, arg.TeamA, arg.TeamB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinishedBetweenTeamsRow{}
	for rows.Next() {
		var i ListFinishedBetweenTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.UtcKickoff,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.HomeName,
			&i.AwayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastFinishedByTeam = `-- name: ListLastFinishedByTeam :many
SELECT m.id, m.season, m.utc_kickoff, m.home_team_id, m.away_team_id,
       m.home_goals, m.away_goals,
       h.name AS home_name, a.name AS away_name
FROM matches m
JOIN teams h ON h.id = m.home_team_id
JOIN teams a ON a.id = m.away_team_id
WHERE m.status = 'FINISHED'
  AND (m.home_team_id = ?1 OR m.away_team_id = ?1)
ORDER BY m.utc_kickoff DESC, m.id DESC
LIMIT 5
`

type ListLastFinishedByTeamRow struct {
	ID         int64         `json:"id"`
	Season     string        `json:"season"`
	UtcKickoff string        `json:"utc_kickoff"`
	HomeTeamID int64         `json:"home_team_id"`
	AwayTeamID int64         `json:"away_team_id"`
	HomeGoals  sql.NullInt64 `json:"home_goals"`
	AwayGoals  sql.NullInt64 `json:"away_goals"`
	HomeName   string        `json:"home_name"`
	AwayName   string        `json:"away_name"`
}

func (q *Queries) ListLastFinishedByTeam(ctx context.Context, team int64) ([]ListLastFinishedByTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, listLastFinishedByTeam, team)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastFinishedByTeamRow{}
	for rows.Next() {
		var i ListLastFinishedByTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.Season,
			&i.UtcKickoff,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeGoals,
			&i.AwayGoals,
			&i.HomeName,
			&i.AwayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCrosswalk = `-- name: UpsertCrosswalk :one
INSERT INTO id_crosswalk (team_id, comp_code, provider, provider_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(team_id, provider) DO UPDATE SET
    provider_id = excluded.provider_id,
    comp_code = excluded.comp_code
RETURNING team_id, comp_code, provider, provider_id
`

type UpsertCrosswalkParams struct {
	TeamID     sql.NullInt64  `json:"team_id"`
	CompCode   sql.NullString `json:"comp_code"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
}

func (q *Queries) UpsertCrosswalk(ctx context.Context, arg UpsertCrosswalkParams) (IDCrosswalk, error) {
	row := q.db.QueryRowContext(ctx, upsertCrosswalk,
		arg.TeamID,
		arg.CompCode,
		arg.Provider,
		arg.ProviderID,
	)
	var i IDCrosswalk
	err := row.Scan(
		&i.TeamID,
		&i.CompCode,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const upsertEloRating = `-- name: UpsertEloRating :exec
INSERT INTO elo_ratings (team_id, rating, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(team_id) DO UPDATE SET
    rating = excluded.rating,
    updated_at = excluded.updated_at
`

type UpsertEloRatingParams struct {
	TeamID    int64   `json:"team_id"`
	Rating    float64 `json:"rating"`
	UpdatedAt string  `json:"updated_at"`
}

func (q *Queries) UpsertEloRating(ctx context.Context, arg UpsertEloRatingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEloRating, arg.TeamID, arg.Rating, arg.UpdatedAt)
	return err
}
